name: CommandRewriter
main: me.minotopia.commandrewriter.CRPlugin
author: HomerBond005
authors: [MinoTopia, Janmm14]
version: '${project.version}'
commands:
    cr:
        description: Rewrite commands
